### ISSUE TITLE
Request: auto click

### ISSUE THREAD

**Issue by EnricoBara** [AndrewParkes/BlockAllSteamInvites#1]
Hi I was working on a similar script but it only ignore lvl 0 accounts. 
I also added a simple "refresh page then click on INGORE ALL button" for automatically clean up all the spam invites.

Do you think you can implement a similar automatic function in your script? Obviously the invites page has to be open IMO.

Regards

**Comment by AndrewParkes** [comment]
So you are wanting to automatically refresh the page and call certain functions or just the ignore all function?

**Comment by EnricoBara** [comment]
Thank you for your reply, I'd like to automatically ignore/block private
profiles and lvl 0. I think the only way is refreshing the page and calling
a "click" function on 2 button but maybe I'm wrong.

Best regards

**Comment by AndrewParkes** [comment]
Ok Ill think about it and try implement something like that as soon as I can

**Comment by EnricoBara** [comment]
Thank you so much I really appreciate it, hope this function won't be
useful only to me.

**Comment by AndrewParkes** [comment]
Sorry its taking long just in the middle of exams and havent had much extra time. I do have an idea on how I want to implement it and will try get it done as soon as I can.

**Comment by EnricoBara** [comment]
Hey mate no problems I'm not on hurry :)  I just given you a suggestion and
I appreciate very much you take care on it. Good luck to your exams!

 | enrico baravelli

2015-05-24 23:18 GMT+02:00 AndrewParkes notifications@github.com:

**Comment by AndrewParkes** [comment]
I believe I have implemented what you are asking for.
Basically by double clicking on each of the functions except Ignore all and block user at level the name will highlight (Will change the styling at a later stage) this means it is active for page refresh calling.

I suggest using something such as Refresh Monkey by Tejji (https://chrome.google.com/webstore/detail/refresh-monkey/ljngnafhejmefmijjoedbclkadhacebd?hl=en) in chrome to refresh the page. I will try an implement a refresher later.

Hope you like it. 
I haven't tested it much but it theoretically should work

**Comment by EnricoBara** [comment]
Thank you very much for the credit too! I'll try it as soon as possible. For refreshing I'm using a tamper script for autobump my trades on D2L (one every 5 minutes). Here's the code I use for refreshing the page after 1 minute (it is sufficient adding this line at the end of the script):

setTimeout(function(){ location.reload(); }, 6*1000);

**Comment by AndrewParkes** [comment]
Pleasure. Let me know if you want anther name to be displayed.
I want to add a refresh function to the script but I want the user to be able to enter the time so that it doesnt seem to randomly refresh without them knowing.
Thank you again for the input.
If you have more suggestions please fell free to let me know :smile:

**Comment by EnricoBara** [comment]
EnricoBara is perfect thanks ;)
Oh yeah indeed I'm not as expert as you in tamper, I let you have a
"pleasure" to add this function eheh
Keep going on your amazing work mate, If I have some suggestion I'll be
glad to let you know!

Best regards for your fast communication!

 | enrico baravelli

2015-06-08 19:43 GMT+02:00 AndrewParkes notifications@github.com:
